<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Recurrent Events • pammtools</title>
<!-- favicons --><link rel="icon" type="image/png" sizes="16x16" href="../favicon-16x16.png">
<link rel="icon" type="image/png" sizes="32x32" href="../favicon-32x32.png">
<link rel="apple-touch-icon" type="image/png" sizes="180x180" href="../apple-touch-icon.png">
<link rel="apple-touch-icon" type="image/png" sizes="120x120" href="../apple-touch-icon-120x120.png">
<link rel="apple-touch-icon" type="image/png" sizes="76x76" href="../apple-touch-icon-76x76.png">
<link rel="apple-touch-icon" type="image/png" sizes="60x60" href="../apple-touch-icon-60x60.png">
<!-- jquery --><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script><!-- Bootstrap --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha256-bZLfwXAP04zRMK2BjiO8iu9pf4FbLqX6zitd+tIvLhE=" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha256-nuL8/2cJ5NDSSwnKD8VqreErSWHtnEP9E7AySL+1ev4=" crossorigin="anonymous"></script><!-- bootstrap-toc --><link rel="stylesheet" href="../bootstrap-toc.css">
<script src="../bootstrap-toc.js"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/v4-shims.min.css" integrity="sha256-wZjR52fzng1pJHwx4aV2AO3yyTOXrcDW7jBpJtTwVxw=" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><!-- headroom.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/headroom.min.js" integrity="sha256-AsUX4SJE1+yuDu5+mAVzJbuYNPHj/WroHuZ8Ir/CkE0=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/jQuery.headroom.min.js" integrity="sha256-ZX/yNShbjqsohH1k95liqY9Gd8uOiE1S4vZc+9KQ1K4=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><!-- docsearch --><script src="../docsearch.js"></script><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/docsearch.js/2.6.3/docsearch.min.css" integrity="sha256-QOSRU/ra9ActyXkIBbiIB144aDBdtvXBcNc3OTNuX/Q=" crossorigin="anonymous">
<link href="../docsearch.css" rel="stylesheet">
<script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/jquery.mark.min.js" integrity="sha256-4HLtjeVgH0eIB3aZ9mLYF6E8oU5chNdjU6p6rrXpl9U=" crossorigin="anonymous"></script><meta property="og:title" content="Recurrent Events">
<meta property="og:description" content="pammtools">
<meta property="og:image" content="https://adibender.github.io/pammtools/logo.png">
<meta name="robots" content="noindex">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]--><!-- Global site tag (gtag.js) - Google Analytics --><script async src="https://www.googletagmanager.com/gtag/js?id=UA-44545040-3"></script><script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-44545040-3');
</script>
</head>
<body data-spy="scroll" data-target="#toc">
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">pammtools</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Version">0.5.7.901</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../reference/index.html">Reference</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Articles
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/data-transformation.html">Data transformation</a>
    </li>
    <li>
      <a href="../articles/baseline.html">Estimating the baseline hazard</a>
    </li>
    <li>
      <a href="../articles/basics.html">Basic modeling</a>
    </li>
    <li>
      <a href="../articles/splines.html">Non-linear effects (penalized splines)</a>
    </li>
    <li>
      <a href="../articles/convenience.html">Workflow and convenience functions</a>
    </li>
    <li>
      <a href="../articles/strata.html">Stratified models</a>
    </li>
    <li>
      <a href="../articles/tveffects.html">Time-varying effects (TVEs)</a>
    </li>
    <li>
      <a href="../articles/frailty.html">Frailties (random effects)</a>
    </li>
    <li>
      <a href="../articles/tdcovar.html">Time-dependent covariates (TDCs)</a>
    </li>
    <li>
      <a href="../articles/left-truncation.html">Left-truncated data</a>
    </li>
    <li>
      <a href="../articles/model-evaluation.html">Model evaluation</a>
    </li>
    <li>
      <a href="../articles/cumulative-effects.html">Cumulative effects/Exposure-Lag-Response Associations</a>
    </li>
    <li>
      <a href="../articles/competing-risks.html">Competing Risks</a>
    </li>
    <li>
      <a href="../articles/recurrent-events.html">Recurrent Events</a>
    </li>
    <li>
      <a href="../articles/smj-tutorial.html">Paper: A generalized additive model approach to time-to-event analysis</a>
    </li>
  </ul>
</li>
<li>
  <a href="../news/index.html">News</a>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right">
<li>
  <a href="https://github.com/adibender/pammtools">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
<form class="navbar-form navbar-right hidden-xs hidden-sm" role="search">
        <div class="form-group">
          <input type="search" class="form-control" name="search-input" id="search-input" placeholder="Search..." aria-label="Search for..." autocomplete="off">
</div>
      </form>
      
    </div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      

      </header><script src="recurrent-events_files/accessible-code-block-0.0.1/empty-anchor.js"></script><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1 data-toc-skip>Recurrent Events</h1>
                        <h4 class="author">Jordache Ramjith, Andreas Bender, Kit C.B. Roes &amp; Marianne A. Jonker</h4>
            
            <h4 class="date">2021-11-26</h4>
      
      <small class="dont-index">Source: <a href="https://github.com/adibender/pammtools/blob/master/vignettes/recurrent-events.Rmd"><code>vignettes/recurrent-events.Rmd</code></a></small>
      <div class="hidden name"><code>recurrent-events.Rmd</code></div>

    </div>

    
    
<div id="introduction" class="section level1">
<h1 class="hasAnchor">
<a href="#introduction" class="anchor"></a>Introduction</h1>
<p>We illustrate application of PAMMs in the analysis of the effect of HIV exposure on the time to staphylococcus aureaus infection in children, with possible recurrences. The children are anonymized and random <code>id</code>s were generated. The following packages are used in this analysis:</p>
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va">mgcv</span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://adibender.github.io/pammtools/">pammtools</a></span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://dplyr.tidyverse.org">dplyr</a></span><span class="op">)</span> <span class="co">#data wrangling</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://ggplot2.tidyverse.org">ggplot2</a></span><span class="op">)</span> <span class="co">#visualization</span>
<span class="fu"><a href="https://ggplot2.tidyverse.org/reference/theme_get.html">theme_set</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_bw</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<div id="time-until-staphylococcus-aureaus-infection-in-children" class="section level2">
<h2 class="hasAnchor">
<a href="#time-until-staphylococcus-aureaus-infection-in-children" class="anchor"></a>Time until staphylococcus aureaus infection in children</h2>
<p>The data set (<code>staph</code>), is contained within the <strong><code>pammtools</code></strong> package and includes 374 observations from 137 children (from the Drakenstein child health study) with a maximum of 6 recurrences. The <code>staph</code> data is in longitudinal format reflecting the recurrences for children over different rows. Here</p>
<ul>
<li>
<code>t.start</code> and <code>t.stop</code> indicate the entry and exit time into the risk set for the respective recurrences</li>
<li>
<code>event</code> indicates whether the <span class="math inline">\(k\)</span>-th recurrence was observed (1 = yes, 0 = censored for the <span class="math inline">\(k\)</span>-th recurrence)</li>
<li>
<code>enum</code> is the event number <span class="math inline">\(k\)</span>
</li>
<li>
<code>HIVexposure</code> indicates whether the mother of the child was HIV positive (1 = yes, 0 = no)</li>
</ul>
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/utils/data.html">data</a></span><span class="op">(</span><span class="st">"staph"</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">staph</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 6 × 6
##   id    t.start t.stop event  enum   hiv
##   &lt;fct&gt;   &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 1           0     16     1     1     0
## 2 1          16    324     1     2     0
## 3 1         324    365     0     3     0
## 4 2           0     59     1     1     1
## 5 2          59    157     1     2     1
## 6 2         157    227     1     3     1</code></pre>
<p>The data for the first two children are</p>
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">staph</span> <span class="op"><a href="../reference/%&gt;%.html">%&gt;%</a></span> <span class="fu"><a href="../reference/dplyr_verbs.html">filter</a></span><span class="op">(</span><span class="va">id</span> <span class="op"><a href="https://rdrr.io/r/base/match.html">%in%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"1"</span>, <span class="st">"2"</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 7 × 6
##   id    t.start t.stop event  enum   hiv
##   &lt;fct&gt;   &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 1           0     16     1     1     0
## 2 1          16    324     1     2     0
## 3 1         324    365     0     3     0
## 4 2           0     59     1     1     1
## 5 2          59    157     1     2     1
## 6 2         157    227     1     3     1
## 7 2         227    368     0     4     1</code></pre>
</div>
<div id="transformation-to-ped-format" class="section level2">
<h2 class="hasAnchor">
<a href="#transformation-to-ped-format" class="anchor"></a>Transformation to PED format</h2>
<p>In order to apply PAMMs to recurrent events, we first transform the data to the <em>piece-wise exponential data</em> (PED) format (see <a href="https://adibender.github.io/pammtools/articles/data-transformation.html">here</a> for details). We use the <code><a href="../reference/as_ped.html">as_ped()</a></code> function in <strong><code>pammtools</code></strong>. For the data transformation in the recurrent events context, we first need to decide whether analysis should be performed on the calendar- or gap-time scale. This is controlled by the <code>timescale</code> argument (see below). For these data, we use the gap-time.</p>
<p>The individual inputs for the data transformation are given as follows:</p>
<ul>
<li>
<code>formula</code>: specifies the <code>Surv</code> object on the left hand side which contains information about the risk set entry and exit times as well as the event indicator; and the variables that should be retained in the data set after data transformation. Note that the variables <code>id</code> and <code>enum</code> will be retained in the data without specification.</li>
<li>
<code>id</code>: specifies the variable in the data set the indicates individual subjects</li>
<li>
<code>data</code>: the data to be transformed</li>
<li>
<code>transition</code>: the variable that indicates transitions from one state to another (here state transitions are transitions from event number <span class="math inline">\(k-1\)</span> to <span class="math inline">\(k\)</span>)</li>
<li>
<code>timescale</code>: the time scale of the output data (defaults to gap time)</li>
<li>
<code>max_time</code>: The maximum time considered. All observations with <span class="math inline">\(t&gt;max\_time\)</span> will be set to <code>max_time</code> and their event indicator set to <span class="math inline">\(0\)</span>. Here we restrict the follow-up to <code>366</code> days, as it marks one year under observation and few children were under observation beyond that time.</li>
<li>
<code>cut</code>: This argument is unspecified here, but could be used to control the time points at which the follow-up is partitioned. If unspecified, all unique event times are used as cut points.</li>
</ul>
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">ped</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/as_ped.html">as_ped</a></span><span class="op">(</span>
  formula     <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/survival/man/Surv.html">Surv</a></span><span class="op">(</span><span class="va">t.start</span>,<span class="va">t.stop</span>,<span class="va">event</span><span class="op">)</span> <span class="op">~</span> <span class="va">hiv</span>,
  id          <span class="op">=</span> <span class="st">"id"</span>,
  data        <span class="op">=</span> <span class="va">staph</span>,
  transition  <span class="op">=</span> <span class="st">"enum"</span>,
  timescale   <span class="op">=</span> <span class="st">"gap"</span>,
  max_time    <span class="op">=</span> <span class="fl">366</span><span class="op">)</span></code></pre></div>
<p>The resulting data for the first two infants is indicated below (we show the first and last observation of each infant for each event number they were at risk):</p>
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">ped</span> <span class="op"><a href="../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="../reference/dplyr_verbs.html">filter</a></span><span class="op">(</span><span class="va">id</span> <span class="op"><a href="https://rdrr.io/r/base/match.html">%in%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"1"</span>, <span class="st">"2"</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="../reference/dplyr_verbs.html">group_by</a></span><span class="op">(</span><span class="va">id</span>, <span class="va">enum</span><span class="op">)</span> <span class="op"><a href="../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="../reference/dplyr_verbs.html">slice</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fu"><a href="https://dplyr.tidyverse.org/reference/context.html">n</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 14 × 8
## # Groups:   id, enum [7]
##    id    tstart  tend interval  offset ped_status   hiv  enum
##    &lt;fct&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;fct&gt;      &lt;dbl&gt;      &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
##  1 1          0     1 (0,1]      0              0     0     1
##  2 1         15    16 (15,16]    0              1     0     1
##  3 1          0     1 (0,1]      0              0     0     2
##  4 1        295   308 (295,308]  2.56           1     0     2
##  5 1          0     1 (0,1]      0              0     0     3
##  6 1         40    41 (40,41]    0              0     0     3
##  7 2          0     1 (0,1]      0              0     1     1
##  8 2         57    59 (57,59]    0.693          1     1     1
##  9 2          0     1 (0,1]      0              0     1     2
## 10 2         97    98 (97,98]    0              1     1     2
## 11 2          0     1 (0,1]      0              0     1     3
## 12 2         69    70 (69,70]    0              1     1     3
## 13 2          0     1 (0,1]      0              0     1     4
## 14 2        140   141 (140,141]  0              0     1     4</code></pre>
</div>
<div id="id" class="section level2">
<h2 class="hasAnchor">
<a href="#id" class="anchor"></a>Baseline model</h2>
<div id="model-specification" class="section level3">
<h3 class="hasAnchor">
<a href="#model-specification" class="anchor"></a>Model specification</h3>
<p>We first model the baseline hazards over time. Biologically, the infection incidence in gap time may be different for the first event compared with the recurrences. However, estimation of the baseline hazard for each of the event numbers is not useful/feasible since only a few subjects experienced 3 or more events. Therefore, we will create a new variable to indicate whether the event a child is at risk for is the first event or a recurrence. Note, however, that we do this after PED data transformation and use the full information to create the PED data. We only use <code>enum_strata</code> for stratification when estimating the baseline hazard.</p>
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">ped</span> <span class="op">&lt;-</span> <span class="va">ped</span> <span class="op"><a href="../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="../reference/dplyr_verbs.html">mutate</a></span><span class="op">(</span>enum_strata <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">as.factor</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/ifelse.html">ifelse</a></span><span class="op">(</span><span class="va">enum</span> <span class="op">&gt;</span> <span class="fl">1</span>,<span class="st">"recurrent"</span>,<span class="st">"first"</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<p>Using this data, we fit the following model</p>
<p><span class="math display">\[
\lambda(t,k|z_i) = \exp(\beta_{0k} + f_{0,k}(t) + z_i),
\]</span></p>
<p>where <span class="math inline">\(z_i\sim N(0, \sigma_z^2)\)</span> are Gaussian, child specific random effects that account for child-specific frailty and <span class="math inline">\(\beta_{0k}\)</span> and <span class="math inline">\(f_{0k}\)</span> are the constant (intercept) and non-linear parts of the log-baseline hazard of the <span class="math inline">\(k\)</span>-th event. Given the data transformation, this is equivalent to fitting a stratified PAM (see <a href="https://adibender.github.io/pammtools/articles/strata.html">here</a> for details), where stratification is done w.r.t. to <code>enum_strata</code>.</p>
</div>
<div id="fitting-the-model" class="section level3">
<h3 class="hasAnchor">
<a href="#fitting-the-model" class="anchor"></a>Fitting the model</h3>
<p>Details on the model specification in <strong><code>R</code></strong> are given below. Note that we use the <code>pamm</code> function to fit the model, which is a wrapper to <code><a href="https://rdrr.io/pkg/mgcv/man/gam.html">mgcv::gam</a></code> or <code><a href="https://rdrr.io/pkg/mgcv/man/bam.html">mgcv::bam</a></code>, but direct modeling of the data using any suitable package/function would also be possible. The other arguments are passed to the respective fitting function.</p>
<p>In the formula argument,</p>
<ul>
<li>
<code>s(tend, by = enum_strata)</code> indicates the non-linear smooth functions, estimated via penalized splines (with thin-plate spline basis functions). By using <code>by=enum_strata</code> inside <code><a href="https://rdrr.io/pkg/mgcv/man/s.html">s()</a></code> and including <code>enum_strata</code> as a fixed effect in the model, we are modeling stratified smooth functions (i.e., stratified baseline hazards) for first and recurrent events respectively, and</li>
<li>
<code>s(id, bs = "re")</code> indicates a random effect (frailty) for each child.</li>
</ul>
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">pamm0</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/pamm.html">pamm</a></span><span class="op">(</span>
  formula  <span class="op">=</span> <span class="va">ped_status</span> <span class="op">~</span> <span class="va">enum_strata</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/pkg/mgcv/man/s.html">s</a></span><span class="op">(</span><span class="va">tend</span>, by <span class="op">=</span> <span class="va">enum_strata</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/pkg/mgcv/man/s.html">s</a></span><span class="op">(</span><span class="va">id</span>, bs <span class="op">=</span> <span class="st">"re"</span><span class="op">)</span>,
  data     <span class="op">=</span> <span class="va">ped</span>,
  engine   <span class="op">=</span> <span class="st">"bam"</span>,
  method   <span class="op">=</span> <span class="st">"fREML"</span>,
  discrete <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></code></pre></div>
<p>As usual for <strong><code>mgcv</code></strong> objects, the resulting model summary output shown below is separated into two parts, one for the “parametric coefficients” and one for the “smooth terms”. In case of smooth terms, the estimated degrees of freedom (edf) gives us an idea of how “wiggly” the respective smooth functions are, and the p-values test whether overall these are different from a flat line <span class="citation">(Wood <a href="#ref-wood_p-values_2013" role="doc-biblioref">2013</a>)</span>. For the random effects terms, we report their estimated variances (<code>gam.vcomp</code>) and p-values (summary output). From the output, we see that the random effects are statistically insignificant <span class="math inline">\((p=0.249)\)</span>.</p>
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">pamm0</span><span class="op">)</span></code></pre></div>
<pre><code>## 
## Family: poisson 
## Link function: log 
## 
## Formula:
## ped_status ~ enum_strata + s(tend, by = enum_strata) + s(id, 
##     bs = "re")
## 
## Parametric coefficients:
##                      Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)           -4.9287     0.1213  -40.62  &lt; 2e-16 ***
## enum_stratarecurrent  -1.0991     0.1857   -5.92 3.23e-09 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Approximate significance of smooth terms:
##                                 edf  Ref.df Chi.sq p-value    
## s(tend):enum_stratafirst      1.995   2.487  35.69 &lt; 2e-16 ***
## s(tend):enum_stratarecurrent  6.101   7.240  33.49 3.7e-05 ***
## s(id)                        14.052 136.000  15.17   0.249    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## R-sq.(adj) =  -0.0265   Deviance explained = -0.97%
## fREML =  18453  Scale est. = 1         n = 18889</code></pre>
<p>The standard deviation of the random effects is also relatively small and can be extracted using the <code>gam.vcomp</code> command:</p>
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/mgcv/man/gam.vcomp.html">gam.vcomp</a></span><span class="op">(</span><span class="va">pamm0</span><span class="op">)</span></code></pre></div>
<pre><code>## 
## Standard deviations and 0.95 confidence intervals:
## 
##                                   std.dev        lower       upper
## s(tend):enum_stratafirst     0.0005741588 8.308116e-05 0.003967907
## s(tend):enum_stratarecurrent 0.0062687807 2.563565e-03 0.015329284
## s(id)                        0.2565797067 4.015591e-02 1.639438617
## 
## Rank: 3/3</code></pre>
<p>The results indicate that random effects are not required in this model. We therefore omit the random effects in the following.</p>
<div class="sourceCode" id="cb15"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">pam0</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/update.html">update</a></span><span class="op">(</span><span class="va">pamm0</span>, <span class="va">.</span><span class="op">~</span><span class="va">.</span> <span class="op">-</span> <span class="fu"><a href="https://rdrr.io/pkg/mgcv/man/s.html">s</a></span><span class="op">(</span><span class="va">id</span>, bs <span class="op">=</span> <span class="st">"re"</span><span class="op">)</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">pam0</span><span class="op">)</span></code></pre></div>
<pre><code>## 
## Family: poisson 
## Link function: log 
## 
## Formula:
## ped_status ~ enum_strata + s(tend, by = enum_strata)
## 
## Parametric coefficients:
##                      Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)           -5.0624     0.1231 -41.124  &lt; 2e-16 ***
## enum_stratarecurrent  -0.8860     0.1801  -4.919 8.71e-07 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Approximate significance of smooth terms:
##                                edf Ref.df Chi.sq  p-value    
## s(tend):enum_stratafirst     2.099  2.616  41.71  &lt; 2e-16 ***
## s(tend):enum_stratarecurrent 6.099  7.238  33.07 3.98e-05 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## R-sq.(adj) =  -0.0276   Deviance explained = -2.34%
## fREML =  18453  Scale est. = 1         n = 18889</code></pre>
</div>
<div id="estimates-over-time-and-visualization" class="section level3">
<h3 class="hasAnchor">
<a href="#estimates-over-time-and-visualization" class="anchor"></a>Estimates over time and visualization</h3>
<p>To obtain and visualize any quantity based on the fitted model, it is easiest to create a suitable data set and calculate the quantity of interest. <strong><code>pammtools</code></strong> provides the respective convenience functions.</p>
<p>Below we illustrate the calculation and visualization of the baseline hazard over time, where we use</p>
<ul>
<li>
<code>make_newdata</code> to create a data set with one row for each unique event time used when fitting the model, stratified by event stratum. <code>make_newdata</code> constructs a combination of the variables specified (here unique values of <code>tend</code> for each value of <code>enum_strata</code>, similar to <code>expand.grid</code>, and sets all other variables to mean and modus values, if applicable). It is also aware of the specific PED structure.</li>
<li>use the <code>add_hazard</code> function to augment the created data set with the predicted hazard and respective confidence intervals.</li>
</ul>
<p>Once the data is created and augmented with the predicted hazard, we can use standard visualization function to create the graphics:</p>
<div class="sourceCode" id="cb17"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">newdata</span> <span class="op">&lt;-</span> <span class="va">ped</span> <span class="op"><a href="../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="../reference/make_newdata.html">make_newdata</a></span><span class="op">(</span>
    tend <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/unique.html">unique</a></span><span class="op">(</span><span class="va">tend</span><span class="op">)</span>,
    enum_strata <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/unique.html">unique</a></span><span class="op">(</span><span class="va">enum_strata</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="../reference/add_hazard.html">add_hazard</a></span><span class="op">(</span><span class="va">pamm0</span>, type <span class="op">=</span> <span class="st">"response"</span><span class="op">)</span>

<span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">newdata</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">tend</span><span class="op">/</span><span class="op">(</span><span class="fl">365.25</span><span class="op">/</span><span class="fl">12</span><span class="op">)</span>, y <span class="op">=</span> <span class="va">hazard</span><span class="op">*</span><span class="fl">365.25</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_line</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_ribbon.html">geom_ribbon</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>ymin  <span class="op">=</span> <span class="va">ci_lower</span><span class="op">*</span><span class="fl">365.25</span>, ymax <span class="op">=</span> <span class="va">ci_upper</span><span class="op">*</span><span class="fl">365.25</span><span class="op">)</span>, alpha <span class="op">=</span> <span class="fl">.3</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">ylab</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/expression.html">expression</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/grDevices/plotmath.html">hat</a></span><span class="op">(</span><span class="va">h</span><span class="op">)</span><span class="op">(</span><span class="va">t</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">xlab</a></span><span class="op">(</span><span class="st">"Time (months)"</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_continuous.html">scale_x_continuous</a></span><span class="op">(</span>limits <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>, <span class="fl">12.5</span><span class="op">)</span>,breaks<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span><span class="op">(</span><span class="fl">0</span>,<span class="fl">12</span>,<span class="fl">2</span><span class="op">)</span>,expand<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>,<span class="fl">0</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/facet_wrap.html">facet_wrap</a></span><span class="op">(</span><span class="op">~</span><span class="va">enum_strata</span><span class="op">)</span></code></pre></div>
<p><img src="recurrent-events_files/figure-html/unnamed-chunk-11-1.png" width="672" style="display: block; margin: auto;"></p>
<p>We can see, that the hazard for the first event is high in the beginning and declines over time, as most children will have had the first infection after one year of life. Consequently, the hazard for recurrence is low in the beginning and increases over time before it flattens out after about two months.</p>
<p>Calculation of survival probabilities works equivalently, except that we use the <code>add_surv_prob</code> function instead of <code>add_hazard</code>. Note that calculating the survival probability involves calculating a cumulative hazard. Thus, when there is a grouping structure in the data (here the different strata), we have to group by this variable before we calculate cumulative hazards or survival probabilities. Note also, that we use <code>geom_surv</code> in order to force the function to start at a survival probability of 1.</p>
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">newdata</span> <span class="op">&lt;-</span><span class="va">newdata</span> <span class="op"><a href="../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="../reference/dplyr_verbs.html">group_by</a></span><span class="op">(</span><span class="va">enum_strata</span><span class="op">)</span> <span class="op"><a href="../reference/%&gt;%.html">%&gt;%</a></span>
  <span class="fu"><a href="../reference/add_surv_prob.html">add_surv_prob</a></span><span class="op">(</span><span class="va">pamm0</span><span class="op">)</span>

<span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">newdata</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">tend</span><span class="op">/</span><span class="op">(</span><span class="fl">365.25</span><span class="op">/</span><span class="fl">12</span><span class="op">)</span>, y <span class="op">=</span> <span class="va">surv_prob</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="../reference/geom_hazard.html">geom_surv</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_ribbon.html">geom_ribbon</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>ymin  <span class="op">=</span> <span class="va">surv_lower</span>, ymax <span class="op">=</span> <span class="va">surv_upper</span><span class="op">)</span>, alpha <span class="op">=</span> <span class="fl">.3</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">ylab</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/expression.html">expression</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/grDevices/plotmath.html">hat</a></span><span class="op">(</span><span class="va">S</span><span class="op">)</span><span class="op">(</span><span class="va">t</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">xlab</a></span><span class="op">(</span><span class="st">"Time (months)"</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_continuous.html">scale_x_continuous</a></span><span class="op">(</span>limits <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>, <span class="fl">12.1</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/facet_wrap.html">facet_wrap</a></span><span class="op">(</span><span class="op">~</span><span class="va">enum_strata</span><span class="op">)</span></code></pre></div>
<p><img src="recurrent-events_files/figure-html/unnamed-chunk-12-1.png" width="672" style="display: block; margin: auto;"></p>
</div>
</div>
<div id="modeling-the-effects-of-hiv-assuming-proportional-hazards" class="section level2">
<h2 class="hasAnchor">
<a href="#modeling-the-effects-of-hiv-assuming-proportional-hazards" class="anchor"></a>Modeling the effects of HIV assuming proportional hazards</h2>
<p>The HIV exposure variable indicates whether children were HIV exposed and uninfected (HEU) by being born to HIV positive mothers or HIV uninfected (HU). We will fit this model in the PAMM framework to evaluate the effect of HIV exposure while assuming proportional hazards. This means that the effects of HIV shift the log-hazard by some constant over time. We fit two models. In the first model, we assume that the hazard ratio is the same for first and recurrent infections. In the second model, we allow different hazard ratios for first and recurrent infections, but we still assume both these hazard ratios are proportional over time.</p>
<div id="model-1" class="section level3">
<h3 class="hasAnchor">
<a href="#model-1" class="anchor"></a>Model 1</h3>
<div class="sourceCode" id="cb19"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">pam1</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/pamm.html">pamm</a></span><span class="op">(</span>
  formula  <span class="op">=</span> <span class="va">ped_status</span> <span class="op">~</span> <span class="va">enum_strata</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/pkg/mgcv/man/s.html">s</a></span><span class="op">(</span><span class="va">tend</span>, by <span class="op">=</span> <span class="va">enum_strata</span><span class="op">)</span> <span class="op">+</span> <span class="va">hiv</span>,
  data     <span class="op">=</span> <span class="va">ped</span>,
  engine   <span class="op">=</span> <span class="st">"bam"</span>,
  method   <span class="op">=</span> <span class="st">"fREML"</span>,
  discrete <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>

<span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">pam1</span><span class="op">)</span></code></pre></div>
<pre><code>## 
## Family: poisson 
## Link function: log 
## 
## Formula:
## ped_status ~ enum_strata + s(tend, by = enum_strata) + hiv
## 
## Parametric coefficients:
##                      Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)           -5.1351     0.1303 -39.416  &lt; 2e-16 ***
## enum_stratarecurrent  -0.8779     0.1801  -4.874 1.09e-06 ***
## hiv                    0.2681     0.1434   1.870   0.0615 .  
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Approximate significance of smooth terms:
##                                edf Ref.df Chi.sq  p-value    
## s(tend):enum_stratafirst     2.121  2.643  41.78  &lt; 2e-16 ***
## s(tend):enum_stratarecurrent 6.084  7.224  33.22 3.71e-05 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## R-sq.(adj) =  -0.0279   Deviance explained = -2.18%
## fREML =  18453  Scale est. = 1         n = 18889</code></pre>
<p>We can see that estimated effect of HIV exposure in terms of the hazard ratio is <span class="math inline">\(HR=\exp(0.2681)=1.31\;(p=0.062)\)</span>.</p>
</div>
<div id="model-2" class="section level3">
<h3 class="hasAnchor">
<a href="#model-2" class="anchor"></a>Model 2</h3>
<div class="sourceCode" id="cb21"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">pam2</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/pamm.html">pamm</a></span><span class="op">(</span>
  formula  <span class="op">=</span> <span class="va">ped_status</span> <span class="op">~</span> <span class="va">enum_strata</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/pkg/mgcv/man/s.html">s</a></span><span class="op">(</span><span class="va">tend</span>, by <span class="op">=</span> <span class="va">enum_strata</span><span class="op">)</span> <span class="op">+</span> <span class="va">hiv</span><span class="op">:</span><span class="va">enum_strata</span>,
  data     <span class="op">=</span> <span class="va">ped</span>,
  engine   <span class="op">=</span> <span class="st">"bam"</span>,
  method   <span class="op">=</span> <span class="st">"fREML"</span>,
  discrete <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>

<span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">pam2</span><span class="op">)</span></code></pre></div>
<pre><code>## 
## Family: poisson 
## Link function: log 
## 
## Formula:
## ped_status ~ enum_strata + s(tend, by = enum_strata) + hiv:enum_strata
## 
## Parametric coefficients:
##                          Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)              -5.05753    0.13330 -37.940  &lt; 2e-16 ***
## enum_stratarecurrent     -1.03583    0.19753  -5.244 1.57e-07 ***
## enum_stratafirst:hiv     -0.02007    0.21300  -0.094  0.92493    
## enum_stratarecurrent:hiv  0.54272    0.19553   2.776  0.00551 ** 
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Approximate significance of smooth terms:
##                                edf Ref.df Chi.sq  p-value    
## s(tend):enum_stratafirst     2.098  2.615  41.71  &lt; 2e-16 ***
## s(tend):enum_stratarecurrent 6.067  7.208  33.42 3.24e-05 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## R-sq.(adj) =  -0.0274   Deviance explained = -2.01%
## fREML =  18451  Scale est. = 1         n = 18889</code></pre>
<p>We can see that estimated effect of HIV exposure in terms of the hazard ratio is <span class="math inline">\(HR=\exp(-0.0201)=0.98\;(p=0.925)\)</span> for the first infection and <span class="math inline">\(HR=\exp(0.5427)=1.72\;(p=0.006)\)</span> for recurrent infections.</p>
</div>
</div>
<div id="references" class="section level2 unnumbered">
<h2 class="hasAnchor">
<a href="#references" class="anchor"></a>References</h2>
<div id="refs" class="references">
<div id="ref-wood_p-values_2013">
<p>Wood, Simon N. 2013. “On P-Values for Smooth Components of an Extended Generalized Additive Model.” <em>Biometrika</em> 100 (1): 221–28. <a href="https://doi.org/10.1093/biomet/ass048">https://doi.org/10.1093/biomet/ass048</a>.</p>
</div>
</div>
</div>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="pkgdown-sidebar">

        <nav id="toc" data-toggle="toc"><h2 data-toc-skip>Contents</h2>
    </nav>
</div>

</div>



      <footer><div class="copyright">
  <p>Developed by Andreas Bender, Fabian Scheipl, Philipp Kopper.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.6.1.</p>
</div>

      </footer>
</div>

  
<script src="https://cdnjs.cloudflare.com/ajax/libs/docsearch.js/2.6.1/docsearch.min.js" integrity="sha256-GKvGqXDznoRYHCwKXGnuchvKSwmx9SRMrZOTh2g4Sb0=" crossorigin="anonymous"></script><script>
  docsearch({
    
    
    apiKey: 'c3726dcbf089f0b26f496305ed030c22',
    indexName: 'pammtools',
    inputSelector: 'input#search-input.form-control',
    transformData: function(hits) {
      return hits.map(function (hit) {
        hit.url = updateHitURL(hit);
        return hit;
      });
    }
  });
</script>
</body>
</html>
