<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Time-varying effects • pammtools</title>
<!-- jquery --><script src="https://code.jquery.com/jquery-3.1.0.min.js" integrity="sha384-nrOSfDHtoPMzJHjVTdCopGqIqeYETSXhZDFyniQ8ZHcVy08QesyHcnOUpMpqnmWq" crossorigin="anonymous"></script><!-- Bootstrap --><link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script><!-- Font Awesome icons --><link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/1.7.1/clipboard.min.js" integrity="sha384-cV+rhyOuRHc9Ub/91rihWcGmMmCXDeksTtCihMupQHSsi8GIIRDG0ThDc3HGQFJ3" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../jquery.sticky-kit.min.js"></script><script src="../pkgdown.js"></script><!-- docsearch --><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.css">
<link href="../docsearch.css" rel="stylesheet">
<script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/jquery.mark.min.js" integrity="sha256-4HLtjeVgH0eIB3aZ9mLYF6E8oU5chNdjU6p6rrXpl9U=" crossorigin="anonymous"></script><meta property="og:title" content="Time-varying effects">
<meta property="og:description" content="">
<meta property="og:image" content="https://adibender.github.io/pammtools/logo.png">
<meta name="twitter:card" content="summary">
<!-- mathjax --><script src="https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]--><!-- Global site tag (gtag.js) - Google Analytics --><script async src="https://www.googletagmanager.com/gtag/js?id=UA-44545040-3"></script><script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-44545040-3');
</script>
</head>
<body>
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">pammtools</a>
        <span class="label label-default" data-toggle="tooltip" data-placement="bottom" title="Released package">0.1.0</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../index.html">
    <span class="fa fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../reference/index.html">Reference</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Articles
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/baseline.html">Baseline Hazard</a>
    </li>
    <li>
      <a href="../articles/basics.html">Basic Modeling </a>
    </li>
    <li>
      <a href="../articles/convenience.html">Convenience functions for post-processing PAMs</a>
    </li>
    <li>
      <a href="../articles/data-transformation.html">Data Transformation</a>
    </li>
    <li>
      <a href="../articles/frailty.html">Frailty and random effects</a>
    </li>
    <li>
      <a href="../articles/splines.html">Splines</a>
    </li>
    <li>
      <a href="../articles/strata.html">Stratified baseline</a>
    </li>
    <li>
      <a href="../articles/tdcovar.html">Time-dependent covariates</a>
    </li>
    <li>
      <a href="../articles/tveffects.html">Time-varying effects</a>
    </li>
  </ul>
</li>
<li>
  <a href="../news/index.html">Changelog</a>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right">
<li>
  <a href="https://github.com/adibender/pammtools">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
<form class="navbar-form navbar-right" role="search">
        <div class="form-group">
          <input type="search" class="form-control" name="search-input" id="search-input" placeholder="Search..." aria-label="Search for..." autocomplete="off">
</div>
      </form>
      
    </div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      
      </header><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1>Time-varying effects</h1>
                        <h4 class="author">Andreas Bender</h4>
            
            <h4 class="date">2018-05-31</h4>
      
      <small class="dont-index">Source: <a href="https://github.com/adibender/pammtools/blob/master/vignettes/tveffects.Rmd"><code>vignettes/tveffects.Rmd</code></a></small>
      <div class="hidden name"><code>tveffects.Rmd</code></div>

    </div>

    
    
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1-1" data-line-number="1"><span class="kw">library</span>(ggplot2)</a>
<a class="sourceLine" id="cb1-2" data-line-number="2"><span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/theme_get">theme_set</a></span>(<span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/ggtheme">theme_bw</a></span>())</a>
<a class="sourceLine" id="cb1-3" data-line-number="3"><span class="kw">library</span>(tidyr)</a>
<a class="sourceLine" id="cb1-4" data-line-number="4"><span class="kw">library</span>(dplyr)</a>
<a class="sourceLine" id="cb1-5" data-line-number="5"><span class="kw">library</span>(pammtools)</a></code></pre></div>
<pre><code>## Warning: replacing previous import 'dplyr::vars' by 'ggplot2::vars' when
## loading 'pammtools'</code></pre>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb3-1" data-line-number="1"><span class="kw">library</span>(survival)</a>
<a class="sourceLine" id="cb3-2" data-line-number="2"><span class="kw">library</span>(mgcv)</a>
<a class="sourceLine" id="cb3-3" data-line-number="3">Set1    &lt;-<span class="st"> </span>RColorBrewer<span class="op">::</span><span class="kw"><a href="http://www.rdocumentation.org/packages/RColorBrewer/topics/ColorBrewer">brewer.pal</a></span>(<span class="dv">9</span>, <span class="st">"Set1"</span>)</a>
<a class="sourceLine" id="cb3-4" data-line-number="4">Greens  &lt;-<span class="st"> </span>RColorBrewer<span class="op">::</span><span class="kw"><a href="http://www.rdocumentation.org/packages/RColorBrewer/topics/ColorBrewer">brewer.pal</a></span>(<span class="dv">9</span>, <span class="st">"Greens"</span>)</a>
<a class="sourceLine" id="cb3-5" data-line-number="5">Purples &lt;-<span class="st"> </span>RColorBrewer<span class="op">::</span><span class="kw"><a href="http://www.rdocumentation.org/packages/RColorBrewer/topics/ColorBrewer">brewer.pal</a></span>(<span class="dv">9</span>, <span class="st">"Purples"</span>)</a></code></pre></div>
<p>In this vignette we show examples of how to fit time-varying effects of time-constant <strong>continuous</strong> covariates. Note that time-varying effects of time-constant <strong>categorical</strong> variables are analogous to stratified proportional hazards models, where observations from different levels of the categorical variable have different baseline hazards. That setting is described in the <a href="strata.html">stratification vignette</a>. <strong>Note that all time-varying effects in a PAM are still assumed to be piece-wise constant over the intervals used to specify the PAM!</strong></p>
<div id="possible-specifications-of-time-variation" class="section level2">
<h2 class="hasAnchor">
<a href="#possible-specifications-of-time-variation" class="anchor"></a>Possible specifications of time-variation</h2>
<p>In the following we denote the continuous time-constant covariate with <span class="math inline">\(x\)</span> and time with <span class="math inline">\(t\)</span>. A time-varying effect of <span class="math inline">\(x\)</span> can then be specified as an interaction term between <span class="math inline">\(x\)</span> and <span class="math inline">\(t\)</span>, where different levels of complexity and flexibility for this interaction are possible:</p>
<ul>
<li><p><span class="math inline">\(\beta_x\cdot x+\beta_{x:t}\cdot(x\cdot g(t))\)</span>: Linear effect of <span class="math inline">\(x\)</span> with time-variation given by <span class="math inline">\(g(t)\)</span>, where <span class="math inline">\(g(\cdot)\)</span> is a known or pre-specified transformation of time <span class="math inline">\(t\)</span>, e.g. the <span class="math inline">\(\log\)</span>-function.</p></li>
<li><p><span class="math inline">\(f_x(x)\cdot g(t)\)</span>: Non-linear effect of <span class="math inline">\(x\)</span>, (linearly) time-varying with <span class="math inline">\(g(t)\)</span>, where <span class="math inline">\(g(t)\)</span> is a known or pre-specified transformation of time</p></li>
<li><p><span class="math inline">\(f_t(t)\cdot x\)</span>: A <em>varying coefficient model</em> in <span class="math inline">\(x\)</span>, where time-variation is non-linear and estimated from the data. If <span class="math inline">\(x\)</span> is a dummy variable coding for levels of a categorical variable this constitutes a stratified model with a different “baseline” hazard for each category, see the <a href="strata.html"><em>strata</em> vignette</a>.</p></li>
<li><p><span class="math inline">\(f_{x,t}(x,t)\)</span>: A non-linear effect of <span class="math inline">\(x\)</span> that varies non-linearly over time <span class="math inline">\(t\)</span>.</p></li>
</ul>
</div>
<div id="veteran-data-example" class="section level2">
<h2 class="hasAnchor">
<a href="#veteran-data-example" class="anchor"></a>Veteran Data example</h2>
<p>For illustration and comparison we use the <code>veteran</code> data presented in the vignette of the <code>survival</code> package (<code><a href="https://cran.rstudio.com/web/packages/survival/vignettes/timedep.pdf">vignette("timedep", package = "survival")</a></code>). Besides information on survival, the data set contains the Karnofsky performance scores <code>karno</code> (the higher the better), <code>age</code> and whether <code>prior</code> therapy occurred, along with some additional covariates, see <code>help("veteran", package = "survival")</code> for details:</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4-1" data-line-number="1"><span class="co"># for some reason the prior variable is coded 0/10 instead of 0/1</span></a>
<a class="sourceLine" id="cb4-2" data-line-number="2"><span class="kw">data</span>(<span class="st">"veteran"</span>, <span class="dt">package=</span><span class="st">"survival"</span>)</a>
<a class="sourceLine" id="cb4-3" data-line-number="3">veteran &lt;-<span class="st"> </span>veteran <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb4-4" data-line-number="4"><span class="st">  </span><span class="kw"><a href="../reference/dplyr_verbs.html">mutate</a></span>(</a>
<a class="sourceLine" id="cb4-5" data-line-number="5">    <span class="dt">trt   =</span> <span class="dv">1</span><span class="op">*</span>(trt <span class="op">==</span><span class="st"> </span><span class="dv">2</span>),</a>
<a class="sourceLine" id="cb4-6" data-line-number="6">    <span class="dt">prior =</span> <span class="dv">1</span><span class="op">*</span>(prior<span class="op">==</span><span class="dv">10</span>)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb4-7" data-line-number="7"><span class="st">  </span><span class="kw"><a href="../reference/dplyr_verbs.html">filter</a></span>(time <span class="op">&lt;</span><span class="st"> </span><span class="dv">400</span>) <span class="co"># restriction for illustration</span></a>
<a class="sourceLine" id="cb4-8" data-line-number="8"><span class="kw">head</span>(veteran)</a></code></pre></div>
<pre><code>##   trt celltype time status karno diagtime age prior
## 1   0 squamous   72      1    60        7  69     0
## 2   0 squamous  228      1    60        3  38     0
## 3   0 squamous  126      1    60        9  63     1
## 4   0 squamous  118      1    70       11  65     1
## 5   0 squamous   10      1    20        5  49     0
## 6   0 squamous   82      1    40       10  69     1</code></pre>
<div id="extended-cox-model-with-known-shape-of-time-variation-function" class="section level3">
<h3 class="hasAnchor">
<a href="#extended-cox-model-with-known-shape-of-time-variation-function" class="anchor"></a>Extended Cox Model (with known shape of time-variation function)</h3>
<p>To fit a time-varying effect of <code>karno</code> the authors suggest to use the function <span class="math display">\[
f(x_{\text{karno}},t) = \beta_{\text{karno}}\cdot x_{\text{karno}} +
  \beta_{\text{karno},t} \cdot x_{\text{karno}} \cdot \log(t+20).
\]</span> This is an instance of case a) above with <span class="math inline">\(g(t) = \log(t+20).\)</span></p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb6-1" data-line-number="1">vfit &lt;-<span class="st"> </span><span class="kw"><a href="http://www.rdocumentation.org/packages/survival/topics/coxph">coxph</a></span>(</a>
<a class="sourceLine" id="cb6-2" data-line-number="2">  <span class="dt">formula =</span> <span class="kw"><a href="http://www.rdocumentation.org/packages/survival/topics/Surv">Surv</a></span>(time, status) <span class="op">~</span><span class="st"> </span>trt <span class="op">+</span><span class="st"> </span>prior <span class="op">+</span><span class="st"> </span>karno <span class="op">+</span><span class="st"> </span><span class="kw">tt</span>(karno),</a>
<a class="sourceLine" id="cb6-3" data-line-number="3">  <span class="dt">data    =</span> veteran,</a>
<a class="sourceLine" id="cb6-4" data-line-number="4">  <span class="dt">tt      =</span> <span class="cf">function</span>(x, t, ...) x <span class="op">*</span><span class="st"> </span><span class="kw">log</span>(t <span class="op">+</span><span class="st"> </span><span class="dv">20</span>))</a>
<a class="sourceLine" id="cb6-5" data-line-number="5"><span class="kw">coef</span>(vfit)</a></code></pre></div>
<pre><code>##         trt       prior       karno   tt(karno) 
##  0.07914694  0.12051224 -0.15466404  0.02930082</code></pre>
<p>Thus the time-varying component of the effect becomes <span class="math inline">\(\beta_{\text{karno}}+\beta_{\text{karno},t}\cdot\log(t+20) = -0.155 + 0.029\cdot\log(t+20)\)</span>:</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb8-1" data-line-number="1">t &lt;-<span class="st"> </span><span class="kw">seq</span>(<span class="dv">0</span>, <span class="dv">400</span>, <span class="dt">by =</span> <span class="dv">10</span>)</a>
<a class="sourceLine" id="cb8-2" data-line-number="2"><span class="kw">plot</span>(<span class="dt">x =</span> t, <span class="dt">y =</span> <span class="kw">coef</span>(vfit)[<span class="st">"karno"</span>] <span class="op">+</span><span class="st"> </span><span class="kw">coef</span>(vfit)[<span class="st">"tt(karno)"</span>]<span class="op">*</span><span class="kw">log</span>(t <span class="op">+</span><span class="st"> </span><span class="dv">20</span>),</a>
<a class="sourceLine" id="cb8-3" data-line-number="3">  <span class="dt">type =</span> <span class="st">"l"</span>, <span class="dt">ylab =</span> <span class="st">"Beta(t) for karno"</span>, <span class="dt">las =</span> <span class="dv">1</span>, <span class="dt">ylim=</span><span class="kw">c</span>(<span class="op">-</span>.<span class="dv">1</span>, <span class="fl">.05</span>), <span class="dt">col=</span>Set1[<span class="dv">1</span>])</a></code></pre></div>
<p><img src="tveffects_files/figure-html/unnamed-chunk-6-1.png" width="384" style="display: block; margin: auto;"></p>
</div>
<div id="pam-with-known-shape-of-time-variation-function" class="section level3">
<h3 class="hasAnchor">
<a href="#pam-with-known-shape-of-time-variation-function" class="anchor"></a>PAM (with known shape of time-variation function)</h3>
<p>To fit a PAM with equivalent model specification (except for the baseline hazard) we can use</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb9-1" data-line-number="1"><span class="co"># data transformation</span></a>
<a class="sourceLine" id="cb9-2" data-line-number="2">ped &lt;-<span class="st"> </span>veteran <span class="op">%&gt;%</span><span class="st"> </span><span class="kw"><a href="../reference/as_ped.html">as_ped</a></span>(<span class="kw"><a href="http://www.rdocumentation.org/packages/survival/topics/Surv">Surv</a></span>(time, status)<span class="op">~</span>., <span class="dt">id =</span> <span class="st">"id"</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb9-3" data-line-number="3"><span class="st">    </span><span class="kw"><a href="../reference/dplyr_verbs.html">mutate</a></span>(<span class="dt">logt20 =</span> <span class="kw">log</span>(tstart<span class="op">+</span>(tstart<span class="op">-</span>tend)<span class="op">/</span><span class="dv">2</span> <span class="op">+</span><span class="st"> </span><span class="dv">20</span>))</a>
<a class="sourceLine" id="cb9-4" data-line-number="4"><span class="kw">head</span>(ped) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw"><a href="../reference/dplyr_verbs.html">select</a></span>(interval, ped_status, trt, karno, age, prior, logt20)</a></code></pre></div>
<pre><code>##   interval ped_status trt karno age prior   logt20
## 1    (0,1]          0   0    60  69     0 2.970414
## 2    (1,2]          0   0    60  69     0 3.020425
## 3    (2,3]          0   0    60  69     0 3.068053
## 4    (3,4]          0   0    60  69     0 3.113515
## 5    (4,7]          0   0    60  69     0 3.113515
## 6    (7,8]          0   0    60  69     0 3.277145</code></pre>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb11-1" data-line-number="1"><span class="co"># fit model</span></a>
<a class="sourceLine" id="cb11-2" data-line-number="2">pam &lt;-<span class="st"> </span><span class="kw"><a href="http://www.rdocumentation.org/packages/mgcv/topics/gam">gam</a></span>(ped_status <span class="op">~</span><span class="st"> </span><span class="kw"><a href="http://www.rdocumentation.org/packages/mgcv/topics/s">s</a></span>(tend) <span class="op">+</span><span class="st"> </span>trt <span class="op">+</span><span class="st"> </span>prior <span class="op">+</span><span class="st"> </span>karno <span class="op">+</span><span class="st"> </span>karno<span class="op">:</span>logt20,</a>
<a class="sourceLine" id="cb11-3" data-line-number="3">    <span class="dt">data =</span> ped, <span class="dt">offset =</span> offset, <span class="dt">family =</span> <span class="kw">poisson</span>())</a>
<a class="sourceLine" id="cb11-4" data-line-number="4"><span class="kw">cbind</span>(</a>
<a class="sourceLine" id="cb11-5" data-line-number="5">  <span class="dt">pam =</span> <span class="kw">coef</span>(pam)[<span class="dv">2</span><span class="op">:</span><span class="dv">5</span>],</a>
<a class="sourceLine" id="cb11-6" data-line-number="6">  <span class="dt">cox =</span> <span class="kw">coef</span>(vfit))</a></code></pre></div>
<pre><code>##                      pam         cox
## trt           0.04795137  0.07914694
## prior         0.11689785  0.12051224
## karno        -0.15921723 -0.15466404
## karno:logt20  0.03049036  0.02930082</code></pre>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb13-1" data-line-number="1"><span class="co"># compare fits</span></a>
<a class="sourceLine" id="cb13-2" data-line-number="2"><span class="kw">plot</span>(<span class="dt">x =</span> t, <span class="dt">y =</span> <span class="kw">coef</span>(vfit)[<span class="st">"karno"</span>] <span class="op">+</span><span class="st"> </span><span class="kw">coef</span>(vfit)[<span class="st">"tt(karno)"</span>]<span class="op">*</span><span class="kw">log</span>(t <span class="op">+</span><span class="st"> </span><span class="dv">20</span>),</a>
<a class="sourceLine" id="cb13-3" data-line-number="3">  <span class="dt">type =</span> <span class="st">"l"</span>, <span class="dt">ylab =</span> <span class="st">"Beta(t) for karno"</span>, <span class="dt">ylim =</span> <span class="kw">c</span>(<span class="op">-</span>.<span class="dv">1</span>, <span class="fl">.05</span>), <span class="dt">las =</span> <span class="dv">1</span>,</a>
<a class="sourceLine" id="cb13-4" data-line-number="4">  <span class="dt">col =</span> Set1[<span class="dv">1</span>])</a>
<a class="sourceLine" id="cb13-5" data-line-number="5">t_pem &lt;-<span class="st"> </span><span class="kw"><a href="../reference/int_info.html">int_info</a></span>(ped)<span class="op">$</span>tend</a>
<a class="sourceLine" id="cb13-6" data-line-number="6"><span class="kw">lines</span>(<span class="dt">x =</span> t_pem, <span class="dt">y =</span> <span class="kw">coef</span>(pam)[<span class="st">"karno"</span>] <span class="op">+</span><span class="st"> </span><span class="kw">coef</span>(pam)[<span class="st">"karno:logt20"</span>]<span class="op">*</span><span class="kw">log</span>(t_pem <span class="op">+</span><span class="st"> </span><span class="dv">20</span>),</a>
<a class="sourceLine" id="cb13-7" data-line-number="7">  <span class="dt">col =</span> Set1[<span class="dv">2</span>], <span class="dt">type =</span> <span class="st">"s"</span>)</a></code></pre></div>
<p><img src="tveffects_files/figure-html/unnamed-chunk-7-1.png" width="384" style="display: block; margin: auto;"> Both methods yield very similar estimates of the time-varying effect of the Karnofsky-Score, with a reduced hazard for higher-scoring patients at the beginning of the follow-up that diminishes over time and turns into an increased hazard for higher-scoring patients after about day 150.</p>
</div>
<div id="pam-penalized-estimation-of-time-variation-function" class="section level3">
<h3 class="hasAnchor">
<a href="#pam-penalized-estimation-of-time-variation-function" class="anchor"></a>PAM (penalized estimation of time-variation function)</h3>
<p>In case we don’t want to pre-specify which shape the time-dependency should have, we can specify the effect of <code>karno</code> as <span class="math inline">\(f(x_{\text{karno}},t) = f(t)\cdot x_{\text{karno}}\)</span>, where <span class="math inline">\(f(t)\)</span> is estimated from the data:</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb14-1" data-line-number="1"><span class="co"># no need to specify main effect for karno here</span></a>
<a class="sourceLine" id="cb14-2" data-line-number="2">pam2 &lt;-<span class="st"> </span><span class="kw"><a href="http://www.rdocumentation.org/packages/mgcv/topics/gam">gam</a></span>(ped_status <span class="op">~</span><span class="st"> </span><span class="kw"><a href="http://www.rdocumentation.org/packages/mgcv/topics/s">s</a></span>(tend) <span class="op">+</span><span class="st"> </span>trt <span class="op">+</span><span class="st"> </span>prior <span class="op">+</span><span class="st"> </span><span class="kw"><a href="http://www.rdocumentation.org/packages/mgcv/topics/s">s</a></span>(tend, <span class="dt">by =</span> karno),</a>
<a class="sourceLine" id="cb14-3" data-line-number="3">    <span class="dt">data =</span> ped, <span class="dt">offset =</span> offset, <span class="dt">family =</span> <span class="kw">poisson</span>())</a></code></pre></div>
The figure below visualizes the estimate of the time-varying effect of <code>karno</code> for all three models
<details><p><summary><em>Expand here to see R-Code</em></summary></p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb15-1" data-line-number="1">term.df &lt;-<span class="st"> </span>ped <span class="op">%&gt;%</span><span class="st"> </span><span class="kw"><a href="../reference/ped_info.html">ped_info</a></span>() <span class="op">%&gt;%</span><span class="st"> </span><span class="kw"><a href="../reference/add_term.html">add_term</a></span>(pam2, <span class="dt">term =</span> <span class="st">"karno"</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb15-2" data-line-number="2"><span class="st">    </span><span class="kw"><a href="http://dplyr.tidyverse.org/reference/summarise_all.html">mutate_at</a></span>(<span class="kw">c</span>(<span class="st">"fit"</span>, <span class="st">"ci_lower"</span>, <span class="st">"ci_upper"</span>), <span class="kw"><a href="http://dplyr.tidyverse.org/reference/funs.html">funs</a></span>(.<span class="op">/</span>.data<span class="op">$</span>karno)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb15-3" data-line-number="3"><span class="st">    </span><span class="kw"><a href="../reference/dplyr_verbs.html">mutate</a></span>(</a>
<a class="sourceLine" id="cb15-4" data-line-number="4">        <span class="dt">cox.fit =</span> <span class="kw">coef</span>(vfit)[<span class="st">"karno"</span>] <span class="op">+</span><span class="st"> </span><span class="kw">coef</span>(vfit)[<span class="st">"tt(karno)"</span>]<span class="op">*</span><span class="kw">log</span>(tend <span class="op">+</span><span class="st"> </span><span class="dv">20</span>),</a>
<a class="sourceLine" id="cb15-5" data-line-number="5">        <span class="dt">pam.fit =</span> <span class="kw">coef</span>(pam)[<span class="st">"karno"</span>] <span class="op">+</span><span class="st"> </span><span class="kw">coef</span>(pam)[<span class="st">"karno:logt20"</span>]<span class="op">*</span><span class="kw">log</span>(tend <span class="op">+</span><span class="st"> </span><span class="dv">20</span>))</a>
<a class="sourceLine" id="cb15-6" data-line-number="6">gg_tv_karno &lt;-<span class="st"> </span><span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/ggplot">ggplot</a></span>(term.df, <span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/aes">aes</a></span>(<span class="dt">x =</span> tend, <span class="dt">y =</span> fit)) <span class="op">+</span></a>
<a class="sourceLine" id="cb15-7" data-line-number="7"><span class="st">    </span><span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/geom_path">geom_step</a></span>(<span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/aes">aes</a></span>(<span class="dt">col =</span> <span class="st">"PAM with penalized spline"</span>)) <span class="op">+</span></a>
<a class="sourceLine" id="cb15-8" data-line-number="8"><span class="st">    </span><span class="kw"><a href="../reference/geom_stepribbon.html">geom_stepribbon</a></span>(<span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/aes">aes</a></span>(<span class="dt">ymin =</span> ci_lower, <span class="dt">ymax =</span> ci_upper), <span class="dt">alpha =</span> <span class="fl">0.2</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb15-9" data-line-number="9"><span class="st">    </span><span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/geom_path">geom_line</a></span>(<span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/aes">aes</a></span>(<span class="dt">y =</span> cox.fit, <span class="dt">col =</span> <span class="st">"Cox with log-transform"</span>)) <span class="op">+</span></a>
<a class="sourceLine" id="cb15-10" data-line-number="10"><span class="st">    </span><span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/geom_path">geom_step</a></span>(<span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/aes">aes</a></span>(<span class="dt">y =</span> pam.fit, <span class="dt">col =</span> <span class="st">"PAM with log-transform"</span>)) <span class="op">+</span></a>
<a class="sourceLine" id="cb15-11" data-line-number="11"><span class="st">    </span><span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/scale_manual">scale_color_manual</a></span>(<span class="dt">name=</span><span class="st">"Method"</span>, <span class="dt">values =</span> <span class="kw">c</span>(Set1[<span class="dv">1</span><span class="op">:</span><span class="dv">2</span>], <span class="dv">1</span>)) <span class="op">+</span></a>
<a class="sourceLine" id="cb15-12" data-line-number="12"><span class="st">    </span><span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/labs">xlab</a></span>(<span class="st">"t"</span>) <span class="op">+</span><span class="st"> </span><span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/labs">ylab</a></span>(<span class="kw">expression</span>(<span class="kw">hat</span>(f)(t)))</a></code></pre></div>
</details><p><img src="tveffects_files/figure-html/unnamed-chunk-8-1.png" width="624" style="display: block; margin: auto;"></p>
<p>The semi-parametric PAM model estimate for <span class="math inline">\(f(t)\)</span> increases fairly linearly up to day 150 and flattens out at about 0 (i.e., no effect of Karnofsky-Scores on the hazard) afterwards.</p>
</div>
<div id="pam-with-smooth-smoothly-time-varying-effect-of-the-karnosky-score" class="section level3">
<h3 class="hasAnchor">
<a href="#pam-with-smooth-smoothly-time-varying-effect-of-the-karnosky-score" class="anchor"></a>PAM with smooth, smoothly time-varying effect of the Karnosky Score</h3>
<p>To fit a non-linear, non-linearly time-varying effect we can specify a two-dimensional interaction between the covariate of interest (here the Karnofsky-Score and a variable that represents time in the respective interval, e.g. interval end-points) using tensor product terms.</p>
<p>In <code><a href="http://www.rdocumentation.org/packages/mgcv/topics/gam">mgcv::gam</a></code> such two-dimensional effects can be directly used either via <code>te</code> or <code>ti</code> terms in the model specification. The later is especially useful for disentangling the marginal (time-constant) and interaction (time-varying) effects of the respective covariate.</p>
<p>Below we first fit a model using the <code>te</code> specification. Note that we did not include a <code><a href="http://www.rdocumentation.org/packages/mgcv/topics/s">s(tend)</a></code> term here, as the time-variable <code>tend</code> is already present in the <code>te</code> term, thus the effect <code><a href="http://www.rdocumentation.org/packages/mgcv/topics/te">te(tend, karno)</a></code> also includes the <em>shape</em> of the baseline hazard as well. The <em>level</em> of the baseline log hazard is given by the intercept of the model.</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb16-1" data-line-number="1">## Non-linear, non-linearly time-varying effects</a>
<a class="sourceLine" id="cb16-2" data-line-number="2">pam3 &lt;-<span class="st"> </span><span class="kw"><a href="http://www.rdocumentation.org/packages/mgcv/topics/gam">gam</a></span>(</a>
<a class="sourceLine" id="cb16-3" data-line-number="3">  <span class="dt">formula =</span> ped_status <span class="op">~</span><span class="st"> </span>trt <span class="op">+</span><span class="st"> </span>prior <span class="op">+</span><span class="st"> </span><span class="kw"><a href="http://www.rdocumentation.org/packages/mgcv/topics/s">s</a></span>(age) <span class="op">+</span><span class="st"> </span><span class="kw"><a href="http://www.rdocumentation.org/packages/mgcv/topics/te">te</a></span>(tend, karno),</a>
<a class="sourceLine" id="cb16-4" data-line-number="4">  <span class="dt">data   =</span> ped,</a>
<a class="sourceLine" id="cb16-5" data-line-number="5">  <span class="dt">family =</span> <span class="kw">poisson</span>(),</a>
<a class="sourceLine" id="cb16-6" data-line-number="6">  <span class="dt">offset =</span> offset)</a></code></pre></div>
<p>The summary of the model indicates that the estimated bivariate function <span class="math inline">\(\hat{f}(x_{\text{karno}}, t)\)</span> is highly non-linear (<span class="math inline">\(edf \approx 8.9\)</span>):</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb17-1" data-line-number="1"><span class="kw">summary</span>(pam3)</a></code></pre></div>
<pre><code>## 
## Family: poisson 
## Link function: log 
## 
## Formula:
## ped_status ~ trt + prior + s(age) + te(tend, karno)
## 
## Parametric coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept) -4.96563    0.16877 -29.422   &lt;2e-16 ***
## trt          0.11795    0.19881   0.593    0.553    
## prior        0.01467    0.20946   0.070    0.944    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Approximate significance of smooth terms:
##                  edf Ref.df Chi.sq p-value    
## s(age)         1.003  1.006  0.371   0.546    
## te(tend,karno) 8.859 11.182 60.369   1e-08 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## R-sq.(adj) =  0.00423   Deviance explained = 6.92%
## UBRE = -0.83464  Scale est. = 1         n = 5392</code></pre>
<p>The 3D perspective plot can aid interpretation, where y- and x-axes depict the Karnosky-Score and the time respectively and the z-axis displays the contribution of the effect to the log-hazard for each combination of <span class="math inline">\(x_{\text{karno}}\)</span> and <span class="math inline">\(t\)</span>.<a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a></p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb19-1" data-line-number="1"><span class="kw">plot</span>(pam3, <span class="dt">select =</span> <span class="dv">2</span>, <span class="dt">pers =</span> T, <span class="dt">theta =</span> <span class="dv">150</span>, <span class="dt">ticktype =</span> <span class="st">"detailed"</span>)</a></code></pre></div>
<pre><code>## Warning in plot.gam(pam3, select = 2, pers = T, theta = 150, ticktype =
## "detailed"): argument pers is deprecated, please use scheme instead</code></pre>
<p><img src="tveffects_files/figure-html/unnamed-chunk-11-1.png" width="576" style="display: block; margin: auto;"> Such 3D plots are sometimes difficult to interpret, thus we also provide a heat-/contourplot (left panel) with respective slices for fixed values of the Karnofsky-Score (middle panel) and fixed time-points/intervals (right panel) below.</p>
<p>The left panel again depicts the Karnosky-Score on the y-axis and the time on the x-axis. The value of <span class="math inline">\(\hat{f}(x_{\text{karno}}, t)\)</span> is visualized using a color gradient, where blue colors indicate log-hazard decrease and red colors a log-hazard increase. The grayed out areas depict combinations of <code>karno</code> and <code>tend</code> that were not present in the data. Dotted horizontal and vertical lines indicate slices that are displayed in the middle and right panel.</p>
<p>For fixed <span class="math inline">\(t=0\)</span>, we obtain the effect of the Karnofsky-Score on the log-hazard at the beginning of the follow-up (red line left panel), which decreases strongly from low to high values of <span class="math inline">\(x_{\text{karno}}\)</span>. <!-- This result is in line with the estimation
one would obtain fitting a time-constant, non-linear effect of
$f(x_{\text{karno}})$. ABER DAS IST ZUFALL HIER; DAS MUSS JA NICHT SO SEIN...  --></p>
<p>Holding the Karnofsky-Score constant, we can see how the log hazard changes over time for different given values of <span class="math inline">\(x_{\text{karno}}\)</span> (middle panel). For higher values <span class="math inline">\(x_{\text{karno}} &gt;60\)</span> the log-hazard is smaller at the beginning and increases over the course of the follow-up (orange and blue lines middle panel). This is consistent with the time-varying effect of the Karnofsky-Score estimated in the previous section. However, the bivariate function indicates that the log hazard may have a parabolic shape for low <span class="math inline">\(x_{\text{karno}}\)</span> values, decreasing at the beginning and increasing again for later time-points (green line middle panel).</p>
<details><p><summary><em>Expand here to see R-Code</em></summary></p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb21-1" data-line-number="1">## heat map/contour plot</a>
<a class="sourceLine" id="cb21-2" data-line-number="2">te_gg &lt;-<span class="st"> </span><span class="kw"><a href="../reference/gg_tensor.html">gg_tensor</a></span>(pam3) <span class="op">+</span></a>
<a class="sourceLine" id="cb21-3" data-line-number="3"><span class="st">  </span><span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/geom_abline">geom_vline</a></span>(<span class="dt">xintercept =</span> <span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">51</span>, <span class="dv">200</span>), <span class="dt">lty =</span> <span class="dv">3</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb21-4" data-line-number="4"><span class="st">  </span><span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/geom_abline">geom_hline</a></span>(<span class="dt">yintercept =</span> <span class="kw">c</span>(<span class="dv">40</span>, <span class="dv">75</span>, <span class="dv">95</span>), <span class="dt">lty =</span> <span class="dv">3</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb21-5" data-line-number="5"><span class="st">  </span><span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/scale_gradient">scale_fill_gradient2</a></span>(</a>
<a class="sourceLine" id="cb21-6" data-line-number="6">    <span class="dt">name =</span> <span class="kw">expression</span>(<span class="kw">hat</span>(f)(<span class="kw">list</span>(x[<span class="kw">plain</span>(karno)],t))),</a>
<a class="sourceLine" id="cb21-7" data-line-number="7">    <span class="dt">low  =</span> <span class="st">"steelblue"</span>, <span class="dt">high =</span> <span class="st">"firebrick2"</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb21-8" data-line-number="8"><span class="st">  </span><span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/geom_contour">geom_contour</a></span>(<span class="dt">col=</span><span class="st">"grey30"</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb21-9" data-line-number="9"><span class="st">  </span><span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/labs">xlab</a></span>(<span class="st">"t"</span>) <span class="op">+</span><span class="st"> </span><span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/labs">ylab</a></span>(<span class="kw">expression</span>(x[<span class="kw">plain</span>(karno)])) <span class="op">+</span></a>
<a class="sourceLine" id="cb21-10" data-line-number="10"><span class="st">  </span><span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/theme">theme</a></span>(<span class="dt">legend.position  =</span> <span class="st">"bottom"</span>)</a></code></pre></div>
<pre><code>## Scale for 'fill' is already present. Adding another scale for 'fill',
## which will replace the existing scale.</code></pre>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb23-1" data-line-number="1">## plot f(karno, t) for specific slices</a>
<a class="sourceLine" id="cb23-2" data-line-number="2">karno_df &lt;-<span class="st"> </span><span class="kw"><a href="../reference/combine_df.html">combine_df</a></span>(</a>
<a class="sourceLine" id="cb23-3" data-line-number="3">  <span class="kw"><a href="../reference/int_info.html">int_info</a></span>(ped),</a>
<a class="sourceLine" id="cb23-4" data-line-number="4">  <span class="kw"><a href="../reference/dplyr_verbs.html">select</a></span>(<span class="kw"><a href="../reference/sample_info.html">sample_info</a></span>(ped), <span class="op">-</span>karno),</a>
<a class="sourceLine" id="cb23-5" data-line-number="5">  <span class="kw">data.frame</span>(<span class="dt">karno =</span> <span class="kw">c</span>(<span class="dv">40</span>, <span class="dv">75</span>, <span class="dv">95</span>)))</a>
<a class="sourceLine" id="cb23-6" data-line-number="6"></a>
<a class="sourceLine" id="cb23-7" data-line-number="7">karno_df &lt;-<span class="st"> </span>karno_df <span class="op">%&gt;%</span><span class="st"> </span><span class="kw"><a href="../reference/add_term.html">add_term</a></span>(pam3, <span class="dt">term=</span><span class="st">"karno"</span>)</a>
<a class="sourceLine" id="cb23-8" data-line-number="8"></a>
<a class="sourceLine" id="cb23-9" data-line-number="9">karno_gg &lt;-<span class="st"> </span><span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/ggplot">ggplot</a></span>(karno_df, <span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/aes">aes</a></span>(<span class="dt">x=</span>tend, <span class="dt">y=</span>fit)) <span class="op">+</span></a>
<a class="sourceLine" id="cb23-10" data-line-number="10"><span class="st">  </span><span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/geom_path">geom_step</a></span>(<span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/aes">aes</a></span>(<span class="dt">col=</span><span class="kw">factor</span>(karno)), <span class="dt">lwd=</span><span class="fl">1.1</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb23-11" data-line-number="11"><span class="st">  </span><span class="kw"><a href="../reference/geom_stepribbon.html">geom_stepribbon</a></span>(<span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/aes">aes</a></span>(<span class="dt">ymin =</span> ci_lower, <span class="dt">ymax =</span> ci_upper, <span class="dt">fill=</span><span class="kw">factor</span>(karno)), <span class="dt">alpha=</span>.<span class="dv">2</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb23-12" data-line-number="12"><span class="st">  </span><span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/scale_manual">scale_color_manual</a></span>(</a>
<a class="sourceLine" id="cb23-13" data-line-number="13">    <span class="dt">name   =</span> <span class="kw">expression</span>(x[<span class="kw">plain</span>(karno)]),</a>
<a class="sourceLine" id="cb23-14" data-line-number="14">    <span class="dt">values =</span> Greens[<span class="kw">c</span>(<span class="dv">4</span>, <span class="dv">7</span>, <span class="dv">9</span>)]) <span class="op">+</span></a>
<a class="sourceLine" id="cb23-15" data-line-number="15"><span class="st">  </span><span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/scale_manual">scale_fill_manual</a></span>(</a>
<a class="sourceLine" id="cb23-16" data-line-number="16">    <span class="dt">name   =</span> <span class="kw">expression</span>(x[<span class="kw">plain</span>(karno)]),</a>
<a class="sourceLine" id="cb23-17" data-line-number="17">    <span class="dt">values =</span> Greens[<span class="kw">c</span>(<span class="dv">4</span>, <span class="dv">7</span>, <span class="dv">9</span>)]) <span class="op">+</span></a>
<a class="sourceLine" id="cb23-18" data-line-number="18"><span class="st">  </span><span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/labs">ylab</a></span>(<span class="kw">expression</span>(<span class="kw">hat</span>(f)(<span class="kw">list</span>(x[<span class="kw">plain</span>(karno)],t)))) <span class="op">+</span></a>
<a class="sourceLine" id="cb23-19" data-line-number="19"><span class="st">  </span><span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/labs">xlab</a></span>(<span class="st">"t"</span>)<span class="op">+</span><span class="st">  </span><span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/coord_cartesian">coord_cartesian</a></span>(<span class="dt">ylim=</span> <span class="kw">c</span>(<span class="op">-</span><span class="dv">4</span>, <span class="dv">3</span>))<span class="op">+</span></a>
<a class="sourceLine" id="cb23-20" data-line-number="20"><span class="st">  </span><span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/theme">theme</a></span>(<span class="dt">legend.position  =</span> <span class="st">"bottom"</span>)</a>
<a class="sourceLine" id="cb23-21" data-line-number="21"></a>
<a class="sourceLine" id="cb23-22" data-line-number="22">time_df &lt;-ped <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb23-23" data-line-number="23"><span class="st">  </span><span class="kw"><a href="../reference/newdata.html">make_newdata</a></span>(<span class="dt">tend=</span><span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">51</span>, <span class="dv">200</span>), <span class="dt">karno=</span><span class="kw">seq</span>(<span class="dv">20</span>, <span class="dv">100</span>, <span class="dt">by=</span><span class="dv">5</span>)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb23-24" data-line-number="24"><span class="st">  </span><span class="kw"><a href="../reference/add_term.html">add_term</a></span>(pam3, <span class="dt">term=</span><span class="st">"karno"</span>)</a>
<a class="sourceLine" id="cb23-25" data-line-number="25"></a>
<a class="sourceLine" id="cb23-26" data-line-number="26">time_gg &lt;-<span class="st"> </span><span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/ggplot">ggplot</a></span>(time_df, <span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/aes">aes</a></span>(<span class="dt">x=</span>karno)) <span class="op">+</span></a>
<a class="sourceLine" id="cb23-27" data-line-number="27"><span class="st">  </span><span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/geom_path">geom_line</a></span>(<span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/aes">aes</a></span>(<span class="dt">y=</span>fit, <span class="dt">col=</span><span class="kw">factor</span>(tend)), <span class="dt">lwd=</span><span class="fl">1.1</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb23-28" data-line-number="28"><span class="st">  </span><span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/geom_ribbon">geom_ribbon</a></span>(<span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/aes">aes</a></span>(<span class="dt">ymin =</span> ci_lower, <span class="dt">ymax =</span> ci_upper, <span class="dt">fill=</span><span class="kw">factor</span>(tend)), <span class="dt">alpha=</span>.<span class="dv">2</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb23-29" data-line-number="29"><span class="st">  </span><span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/scale_manual">scale_color_manual</a></span>(<span class="dt">name=</span><span class="st">"t"</span>, <span class="dt">values=</span>Purples[<span class="kw">c</span>(<span class="dv">4</span>, <span class="dv">6</span>, <span class="dv">8</span>)]) <span class="op">+</span></a>
<a class="sourceLine" id="cb23-30" data-line-number="30"><span class="st">  </span><span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/scale_manual">scale_fill_manual</a></span>(<span class="dt">name=</span><span class="st">"t"</span>, <span class="dt">values=</span>Purples[<span class="kw">c</span>(<span class="dv">4</span>, <span class="dv">6</span>, <span class="dv">8</span>)]) <span class="op">+</span></a>
<a class="sourceLine" id="cb23-31" data-line-number="31"><span class="st">  </span><span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/labs">ylab</a></span>(<span class="kw">expression</span>(<span class="kw">hat</span>(f)(<span class="kw">list</span>(x[<span class="kw">plain</span>(karno)],t)))) <span class="op">+</span></a>
<a class="sourceLine" id="cb23-32" data-line-number="32"><span class="st">  </span><span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/labs">xlab</a></span>(<span class="kw">expression</span>(x[<span class="kw">plain</span>(karno)])) <span class="op">+</span><span class="st"> </span><span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/coord_cartesian">coord_cartesian</a></span>(<span class="dt">ylim=</span> <span class="kw">c</span>(<span class="op">-</span><span class="dv">4</span>, <span class="dv">3</span>))<span class="op">+</span></a>
<a class="sourceLine" id="cb23-33" data-line-number="33"><span class="st">  </span><span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/theme">theme</a></span>(<span class="dt">legend.position  =</span> <span class="st">"bottom"</span>)</a></code></pre></div>
</details><p><img src="tveffects_files/figure-html/unnamed-chunk-13-1.png" width="672" style="display: block; margin: auto;"></p>
<p>The following figure shows the estimated effect (middle panel) along with a pointwise upper (right) and lower (left) CI. Note that we have to be somewhat cautious with interpretation, considering the large uncertainty of the effect estimate, especially for lower Karnofsky-Scores and later time-points. Also note that the estimate does not include the estimated average time-constant log-hazard (<code>coefficients(pam3)["(Intercept)"]=</code>-4.966) and its uncertainty:</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb24-1" data-line-number="1"><span class="kw"><a href="../reference/gg_tensor.html">gg_tensor</a></span>(pam3, <span class="dt">ci=</span><span class="ot">TRUE</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb24-2" data-line-number="2"><span class="st">  </span><span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/labs">xlab</a></span>(<span class="st">"t"</span>) <span class="op">+</span><span class="st"> </span><span class="kw"><a href="http://www.rdocumentation.org/packages/ggplot2/topics/labs">ylab</a></span>(<span class="kw">expression</span>(x[<span class="kw">plain</span>(karno)]))</a></code></pre></div>
<p><img src="tveffects_files/figure-html/unnamed-chunk-14-1.png" width="672" style="display: block; margin: auto;"></p>
</div>
</div>
<div class="footnotes">
<hr>
<ol>
<li id="fn1"><p>Note that the graphical representation in the 3D wireframe plot as well as the heatmap/contour plots below not exact – these effects are actually step functions over time, with steps at the interval end points <code>tend</code>, since a PAM implies that <em>all</em> time-varying effects are piece-wise constant over the intervals used for the fit. In practice, this subtle difference can be neglected if the intervals are small enough, as in this case.<a href="#fnref1" class="footnote-back">↩</a></p></li>
</ol>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="sidebar">
        <div id="tocnav">
      <h2 class="hasAnchor">
<a href="#tocnav" class="anchor"></a>Contents</h2>
      <ul class="nav nav-pills nav-stacked">
<li><a href="#possible-specifications-of-time-variation">Possible specifications of time-variation</a></li>
      <li><a href="#veteran-data-example">Veteran Data example</a></li>
      </ul>
</div>
      </div>

</div>


      <footer><div class="copyright">
  <p>Developed by Andreas Bender, Fabian Scheipl.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="http://pkgdown.r-lib.org/">pkgdown</a>.</p>
</div>

      </footer>
</div>

  
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.js"></script><script>
  docsearch({
    
    
    apiKey: 'c3726dcbf089f0b26f496305ed030c22',
    indexName: 'pammtools',
    inputSelector: 'input#search-input.form-control',
    transformData: function(hits) {
      return hits.map(function (hit) {
        hit.url = updateHitURL(hit);
        return hit;
      });
    }
  });
</script>
</body>
</html>
